# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# guard 'haml' do
#   watch("slides.haml")
# end

guard 'bundler' do
  watch('Gemfile')
end

guard 'markdown' do  
	watch ("outline.markdown") { "outline.markdown|./outline.html" }
end
